include: package:lint/strict.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "hiddify-core/**"
    - "**.g.dart"
    - "lib/gen/**"
    - "lib/hiddifycore/generated/**"
    - "lib/features/profile/details/json_editor.dart"
    - "tool/riverpod_repro_test.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120

linter:
  rules:
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    avoid_classes_with_only_static_members: false

custom_lint:
  rules:
    # Enable one rule
    - provider_parameters